using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace dotnet_pricing_svc.Models
{

    public class PricingContext : DbContext
    {
        public DbSet<Ticker> Tickers { get; set; } = null!;
        public DbSet<Price> Prices { get; set; } = null!;

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseNpgsql("User ID=postgres;Password=docker;Host=localhost;Port=5432;Database=pricing;Pooling=true;");
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Price>()
                .Property<DateTime>("Date")
                .HasColumnType("timestamp without time zone");

            modelBuilder.Entity<Price>()
                .HasIndex(p => new { p.TickerId, p.Date }, "IX_Price_UQ")
                .IsUnique();
            
            modelBuilder.Entity<Price>()
                .HasOne(p => p.Ticker)
                .WithMany(t => t.Prices)
                .HasForeignKey("TickerId");

            modelBuilder.Entity<Ticker>()
                .HasIndex(t => t.Name, "IX_Ticker_UQ")
                .IsUnique();

            modelBuilder.Entity<Ticker>().HasData(
                new Ticker(){ TickerId =   1, Name = "BOVV11", Type = "ETF" },
                new Ticker(){ TickerId =   2, Name = "BOVA11", Type = "ETF" },
                new Ticker(){ TickerId =   3, Name = "BOVX11", Type = "ETF" },
                new Ticker(){ TickerId =   4, Name = "DIVO11", Type = "ETF" },
                new Ticker(){ TickerId =   5, Name = "IVVB11", Type = "ETF" },
                new Ticker(){ TickerId =   6, Name = "SMAL11", Type = "ETF" },
                new Ticker(){ TickerId =   7, Name = "MATB11", Type = "ETF" },
                new Ticker(){ TickerId =   8, Name = "EURP11", Type = "ETF" },
                new Ticker(){ TickerId =   9, Name = "ASIA11", Type = "ETF" },
                new Ticker(){ TickerId =  10, Name = "XINA11", Type = "ETF" },
                new Ticker(){ TickerId =  11, Name = "ACWI11", Type = "ETF" },
                new Ticker(){ TickerId =  12, Name = "HTEK11", Type = "ETF" },
                new Ticker(){ TickerId =  13, Name = "TECK11", Type = "ETF" },
                new Ticker(){ TickerId =  14, Name = "NASD11", Type = "ETF" },
                new Ticker(){ TickerId =  15, Name = "QBTC11", Type = "ETF" },
                new Ticker(){ TickerId =  16, Name = "HASH11", Type = "ETF" },
                new Ticker(){ TickerId =  17, Name = "XFIX11", Type = "ETF" },
                new Ticker(){ TickerId =  18, Name = "GOLD11", Type = "ETF" },
                new Ticker(){ TickerId =  19, Name = "TECB11", Type = "ETF" },
                new Ticker(){ TickerId =  20, Name = "USTK11", Type = "ETF" },
                new Ticker(){ TickerId =  21, Name = "JOGO11", Type = "ETF" },
                new Ticker(){ TickerId =  22, Name = "USDBRL", Type = "CUR" },
                new Ticker(){ TickerId =  23, Name = "BAAX39", Type = "BDR" },
                new Ticker(){ TickerId =  24, Name = "BEWC39", Type = "BDR" },
                new Ticker(){ TickerId =  25, Name = "BGRT39", Type = "BDR" },
                new Ticker(){ TickerId =  26, Name = "BEEM39", Type = "BDR" },
                new Ticker(){ TickerId =  27, Name = "BIXJ39", Type = "BDR" },
                new Ticker(){ TickerId =  28, Name = "BDVY39", Type = "BDR" },
                new Ticker(){ TickerId =  29, Name = "BIEF39", Type = "BDR" },
                new Ticker(){ TickerId =  30, Name = "BIEV39", Type = "BDR" },
                new Ticker(){ TickerId =  31, Name = "BIVE39", Type = "BDR" },
                new Ticker(){ TickerId =  32, Name = "BMTU39", Type = "BDR" },
                new Ticker(){ TickerId =  33, Name = "BUSR39", Type = "BDR" },
                new Ticker(){ TickerId =  34, Name = "BACW39", Type = "BDR" },
                new Ticker(){ TickerId =  35, Name = "ITLC34", Type = "BDR" },
                new Ticker(){ TickerId =  36, Name = "TSMC34", Type = "BDR" },
                new Ticker(){ TickerId =  37, Name = "DVY",    Type = "ETF_EUA" },
                new Ticker(){ TickerId =  38, Name = "IVV",    Type = "ETF_EUA" },
                new Ticker(){ TickerId =  39, Name = "MCHI",   Type = "ETF_EUA" },
                new Ticker(){ TickerId =  40, Name = "ACWI",   Type = "ETF_EUA" },
                new Ticker(){ TickerId =  41, Name = "EZU",    Type = "ETF_EUA" },
                new Ticker(){ TickerId =  42, Name = "AAXJ",   Type = "ETF_EUA" },
                new Ticker(){ TickerId =  43, Name = "ABCB4",  Type = "ACAO" },
                new Ticker(){ TickerId =  44, Name = "BBAS3",  Type = "ACAO" },
                new Ticker(){ TickerId =  45, Name = "BBDC4",  Type = "ACAO" },
                new Ticker(){ TickerId =  46, Name = "ITSA4",  Type = "ACAO" },
                new Ticker(){ TickerId =  47, Name = "BIDI11", Type = "ACAO" },
                new Ticker(){ TickerId =  48, Name = "CIEL3",  Type = "ACAO" },
                new Ticker(){ TickerId =  49, Name = "SQIA3",   Type = "ACAO" },
                new Ticker(){ TickerId =  50, Name = "B3SA3",   Type = "ACAO" },
                new Ticker(){ TickerId =  51, Name = "TRPL4",   Type = "ACAO" },
                new Ticker(){ TickerId =  52, Name = "ENBR3",   Type = "ACAO" },
                new Ticker(){ TickerId =  53, Name = "EGIE3",   Type = "ACAO" },
                new Ticker(){ TickerId =  54, Name = "TAEE11",   Type = "ACAO" },
                new Ticker(){ TickerId =  55, Name = "ALUP4",   Type = "ACAO" },
                new Ticker(){ TickerId =  56, Name = "NEOE3",   Type = "ACAO" },
                new Ticker(){ TickerId =  57, Name = "CPLE3",   Type = "ACAO" },
                new Ticker(){ TickerId =  58, Name = "ELET3",   Type = "ACAO" },
                new Ticker(){ TickerId =  59, Name = "AERI3",   Type = "ACAO" },
                new Ticker(){ TickerId =  60, Name = "VIVT3",   Type = "ACAO" },
                new Ticker(){ TickerId =  61, Name = "WEGE3",   Type = "ACAO" },
                new Ticker(){ TickerId =  62, Name = "TUPY3",   Type = "ACAO" },
                new Ticker(){ TickerId =  63, Name = "FESA4",   Type = "ACAO" },
                new Ticker(){ TickerId =  64, Name = "SHUL4",   Type = "ACAO" },
                new Ticker(){ TickerId =  65, Name = "LEVE3",   Type = "ACAO" },
                new Ticker(){ TickerId =  66, Name = "MYPK3",   Type = "ACAO" },
                new Ticker(){ TickerId =  67, Name = "POMO3",   Type = "ACAO" },
                new Ticker(){ TickerId =  68, Name = "RAPT4",   Type = "ACAO" },
                new Ticker(){ TickerId =  69, Name = "ECOR3",   Type = "ACAO" },
                new Ticker(){ TickerId =  70, Name = "PETR4",   Type = "ACAO" },
                new Ticker(){ TickerId =  71, Name = "PRIO3",   Type = "ACAO" },
                new Ticker(){ TickerId =  72, Name = "VBBR3",   Type = "ACAO" },
                new Ticker(){ TickerId =  73, Name = "CSNA3",   Type = "ACAO" },
                new Ticker(){ TickerId =  74, Name = "CSAN3",   Type = "ACAO" },
                new Ticker(){ TickerId =  75, Name = "VALE3",   Type = "ACAO" },
                new Ticker(){ TickerId =  76, Name = "COGN3",   Type = "ACAO" },
                new Ticker(){ TickerId =  77, Name = "YDUQ3",   Type = "ACAO" },
                new Ticker(){ TickerId =  78, Name = "SEER3",   Type = "ACAO" },
                new Ticker(){ TickerId =  79, Name = "ANIM3",   Type = "ACAO" },
                new Ticker(){ TickerId =  80, Name = "SBSP3",   Type = "ACAO" },
                new Ticker(){ TickerId =  81, Name = "SAPR11",   Type = "ACAO" },
                new Ticker(){ TickerId =  82, Name = "CSMG3",   Type = "ACAO" },
                new Ticker(){ TickerId =  83, Name = "KLBN11",   Type = "ACAO" },
                new Ticker(){ TickerId =  84, Name = "SUZB3",   Type = "ACAO" },
                new Ticker(){ TickerId =  85, Name = "FLRY3",   Type = "ACAO" },
                new Ticker(){ TickerId =  86, Name = "RADL3",   Type = "ACAO" },
                new Ticker(){ TickerId =  87, Name = "ODPV3",   Type = "ACAO" },
                new Ticker(){ TickerId =  88, Name = "SULA11",   Type = "ACAO" },
                new Ticker(){ TickerId =  89, Name = "HAPV3",   Type = "ACAO" },
                new Ticker(){ TickerId =  90, Name = "RDOR3",   Type = "ACAO" },
                new Ticker(){ TickerId =  91, Name = "IRBR3",   Type = "ACAO" },
                new Ticker(){ TickerId =  92, Name = "BBSE3",   Type = "ACAO" },
                new Ticker(){ TickerId =  93, Name = "MTRE3",   Type = "ACAO" },
                new Ticker(){ TickerId =  94, Name = "CYRE3",   Type = "ACAO" },
                new Ticker(){ TickerId =  95, Name = "MRVE3",   Type = "ACAO" },
                new Ticker(){ TickerId =  96, Name = "EZTC3",   Type = "ACAO" },
                new Ticker(){ TickerId =  97, Name = "JHSF3",   Type = "ACAO" },
                new Ticker(){ TickerId =  98, Name = "GFSA3",   Type = "ACAO" },
                new Ticker(){ TickerId =  99, Name = "TEND3",   Type = "ACAO" },
                new Ticker(){ TickerId = 100, Name = "BRPR3",   Type = "ACAO" },
                new Ticker(){ TickerId = 101, Name = "DXCO3",   Type = "ACAO" },
                new Ticker(){ TickerId = 102, Name = "ABEV3",   Type = "ACAO" },
                new Ticker(){ TickerId = 103, Name = "PCAR3",   Type = "ACAO" },
                new Ticker(){ TickerId = 104, Name = "ASAI3",   Type = "ACAO" },
                new Ticker(){ TickerId = 105, Name = "MDIA3",   Type = "ACAO" },
                new Ticker(){ TickerId = 106, Name = "CAML3",   Type = "ACAO" },
                new Ticker(){ TickerId = 107, Name = "BEEF3",   Type = "ACAO" },
                new Ticker(){ TickerId = 108, Name = "MRFG3",   Type = "ACAO" },
                new Ticker(){ TickerId = 109, Name = "BRFS3",   Type = "ACAO" },
                new Ticker(){ TickerId = 110, Name = "VLID3",   Type = "ACAO" },
                new Ticker(){ TickerId = 111, Name = "LREN3",   Type = "ACAO" },
                new Ticker(){ TickerId = 112, Name = "WHRL3",   Type = "ACAO" },
                new Ticker(){ TickerId = 113, Name = "GUAR3",   Type = "ACAO" },
                new Ticker(){ TickerId = 114, Name = "CGRA3",   Type = "ACAO" },
                new Ticker(){ TickerId = 115, Name = "AMAR3",   Type = "ACAO" },
                new Ticker(){ TickerId = 116, Name = "AMER3",   Type = "ACAO" },
                new Ticker(){ TickerId = 117, Name = "MGLU3",   Type = "ACAO" },
                new Ticker(){ TickerId = 118, Name = "VIIA3",   Type = "ACAO" },
                new Ticker(){ TickerId = 119, Name = "HGTX3",   Type = "ACAO" },
                new Ticker(){ TickerId = 120, Name = "IGTA3",   Type = "ACAO" },
                new Ticker(){ TickerId = 121, Name = "IGTI11",   Type = "ACAO" },
                new Ticker(){ TickerId = 122, Name = "MULT3",   Type = "ACAO" },
                new Ticker(){ TickerId = 123, Name = "BRML3",   Type = "ACAO" },
                new Ticker(){ TickerId = 124, Name = "STBP3",   Type = "ACAO" },
                new Ticker(){ TickerId = 125, Name = "LOGN3",   Type = "ACAO" },
                new Ticker(){ TickerId = 126, Name = "PNVL3",   Type = "ACAO" },
                new Ticker(){ TickerId = 127, Name = "PTBL3",   Type = "ACAO" },
                new Ticker(){ TickerId = 128, Name = "NTCO3",   Type = "ACAO" },
                new Ticker(){ TickerId = 129, Name = "MOVI3",   Type = "ACAO" },
                new Ticker(){ TickerId = 130, Name = "AZUL4",   Type = "ACAO" },
                new Ticker(){ TickerId = 141, Name = "BCFF11",   Type = "FII" },
                new Ticker(){ TickerId = 142, Name = "BRCR11",   Type = "FII" },
                new Ticker(){ TickerId = 143, Name = "JSRE11",   Type = "FII" },
                new Ticker(){ TickerId = 144, Name = "BBPO11",   Type = "FII" },
                new Ticker(){ TickerId = 145, Name = "TEPP11",   Type = "FII" },
                new Ticker(){ TickerId = 146, Name = "CPTS11",   Type = "FII" },
                new Ticker(){ TickerId = 147, Name = "RCRB11",   Type = "FII" },
                new Ticker(){ TickerId = 148, Name = "IRDM11",   Type = "FII" },
                new Ticker(){ TickerId = 149, Name = "HSML11",   Type = "FII" },
                new Ticker(){ TickerId = 150, Name = "PVBI11",   Type = "FII" },
                new Ticker(){ TickerId = 151, Name = "MGFF11",   Type = "FII" },
                new Ticker(){ TickerId = 152, Name = "RBRR11",   Type = "FII" },
                new Ticker(){ TickerId = 153, Name = "RBRL11",   Type = "FII" },
                new Ticker(){ TickerId = 154, Name = "TGAR11",   Type = "FII" },
                new Ticker(){ TickerId = 155, Name = "HBRH11",   Type = "FII" },
                new Ticker(){ TickerId = 156, Name = "KNIP11",   Type = "FII" },
                new Ticker(){ TickerId = 157, Name = "PATL11",   Type = "FII" },
                new Ticker(){ TickerId = 158, Name = "AIEC11",   Type = "FII" },
                new Ticker(){ TickerId = 159, Name = "FVPQ11",   Type = "FII" },
                new Ticker(){ TickerId = 160, Name = "CVBI11",   Type = "FII" },
                new Ticker(){ TickerId = 161, Name = "LVBI11",   Type = "FII" },
                new Ticker(){ TickerId = 162, Name = "VINO11",   Type = "FII" },
                new Ticker(){ TickerId = 163, Name = "HGRU11",   Type = "FII" },
                new Ticker(){ TickerId = 164, Name = "RBED11",   Type = "FII" },
                new Ticker(){ TickerId = 165, Name = "FEXC11",   Type = "FII" },
                new Ticker(){ TickerId = 166, Name = "BTCR11",   Type = "FII" },
                new Ticker(){ TickerId = 167, Name = "KNHY11",   Type = "FII" },
                new Ticker(){ TickerId = 168, Name = "BARI11",   Type = "FII" },
                new Ticker(){ TickerId = 169, Name = "RBRP11",   Type = "FII" },
                new Ticker(){ TickerId = 170, Name = "BTLG11",   Type = "FII" },
                new Ticker(){ TickerId = 171, Name = "KNCR11",   Type = "FII" },
                new Ticker(){ TickerId = 172, Name = "MCCI11",   Type = "FII" },
                new Ticker(){ TickerId = 173, Name = "BRCO11",   Type = "FII" },
                new Ticker(){ TickerId = 174, Name = "FCFL11",   Type = "FII" },
                new Ticker(){ TickerId = 175, Name = "BLMG11",   Type = "FII" },
                new Ticker(){ TickerId = 176, Name = "HGPO11",   Type = "FII" },
                new Ticker(){ TickerId = 177, Name = "ALZR11",   Type = "FII" },
                new Ticker(){ TickerId = 178, Name = "VIUR11",   Type = "FII" },
                new Ticker(){ TickerId = 179, Name = "BPML11",   Type = "FII" },
                new Ticker(){ TickerId = 180, Name = "BCIA11",   Type = "FII" },
                new Ticker(){ TickerId = 181, Name = "XPSF11",   Type = "FII" },
                new Ticker(){ TickerId = 182, Name = "XPCI11",   Type = "FII" },
                new Ticker(){ TickerId = 183, Name = "HGFF11",   Type = "FII" },
                new Ticker(){ TickerId = 184, Name = "VGIR11",   Type = "FII" },
                new Ticker(){ TickerId = 185, Name = "VIFI11",   Type = "FII" },
                new Ticker(){ TickerId = 186, Name = "KNRI11",   Type = "FII" },
                new Ticker(){ TickerId = 187, Name = "HGCR11",   Type = "FII" },
                new Ticker(){ TickerId = 188, Name = "HFOF11",   Type = "FII" },
                new Ticker(){ TickerId = 189, Name = "KFOF11",   Type = "FII" },
                new Ticker(){ TickerId = 190, Name = "MXRF11",   Type = "FII" },
                new Ticker(){ TickerId = 191, Name = "MALL11",   Type = "FII" },
                new Ticker(){ TickerId = 192, Name = "PATC11",   Type = "FII" },
                new Ticker(){ TickerId = 193, Name = "HGRE11",   Type = "FII" },
                new Ticker(){ TickerId = 194, Name = "RBFF11",   Type = "FII" },
                new Ticker(){ TickerId = 195, Name = "SDIL11",   Type = "FII" },
                new Ticker(){ TickerId = 196, Name = "VISC11",   Type = "FII" },
                new Ticker(){ TickerId = 197, Name = "VILG11",   Type = "FII" },
                new Ticker(){ TickerId = 198, Name = "XPIN11",   Type = "FII" },
                new Ticker(){ TickerId = 199, Name = "XPLG11",   Type = "FII" },
                new Ticker(){ TickerId = 200, Name = "HGBS11",   Type = "FII" },
                new Ticker(){ TickerId = 201, Name = "HLOG11",   Type = "FII" },
                new Ticker(){ TickerId = 202, Name = "XPML11",   Type = "FII" }
            );

            modelBuilder.Entity<Price>().HasData(
                new Price() { PriceId = 1, Date = new DateTime(2022, 6, 30), Value = 99.17F, TickerId = 1 }
            );
        }
    }
}